### ISSUE TITLE
No entries found! Check out another form.

### ISSUE THREAD

**Issue by jonathanR79** [sanzeeb3/entries-for-wpforms#1]
Wordpress 5.1
Entries For WPForms 1.45
WPForms Lite Version 1.5.1.1

Hello,

For me the plugin don't do anything. 

"Entries for WPforms" page stay empty.

**Comment by sanzeeb3** [comment]
@jonathanR79  Make sure the form has submitted entries or filter the form containing entries. By default entries of the latest form will appear. Also, note that the plugin will not display any entries submitted prior to this plugin installation.
![filter form](https://user-images.githubusercontent.com/16817248/53462446-a128f780-39f8-11e9-9a4d-7714e9373ec8.png)

**Comment by jonathanR79** [comment]
No sorry, it do not display anything. In the meantime, I have found another plugin that works and do the job. I did install Contact Form Entries plugin after this one and I see 3 entries on my forms in this plugin but still nothing on Entries For WPForms

**Comment by sanzeeb3** [comment]
Fixed.
